version: '3.9'

services:
  nlp-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ${HOME}/.flair:${HOME}/.flair
      - ${HOME}/.rel_cache:${HOME}/.rel_cache:rw
      - ${HOME}/.cache:${HOME}/.cache:rw
      - ${PWD}/data/:/workspace/data
      - /etc/passwd:/etc/passwd:ro
    user: ${USERID}:${GROUPID}
    restart: always
    deploy:
      resources:
        limits:
          memory: 3G
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              capabilities: [ gpu ]
#              device_ids: ['0']
