site_name: "REL: Radboud Entity Linker"

nav:
  - Home: index.md
  - 🔗 Source code: https://github.com/informagi/REL
  - 🔗 Issues: https://github.com/informagi/REL/issues


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: red
      scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/lightbulb
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: red
      scheme: slate
      toggle:
        name: Switch to light mode
        icon: material/lightbulb-outline

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
# - mkdocstrings:
#     # https://mkdocstrings.github.io/usage/
#     handlers:
#       python:
#         import:
#         - https://docs.python.org/3/objects.inv
#         - https://numpy.org/doc/stable/objects.inv
#         - https://docs.scipy.org/doc/scipy/objects.inv
#         - https://pandas.pydata.org/docs/objects.inv
#         selection:
#           docstring_style: numpy
#           docstring_options:
#             ignore_init_summary: yes
#         rendering:
#           show_submodules: no
#           show_source: true
#           docstring_section_style: list
#           members_order: alphabetical
#           show_category_heading: no
#           merge_init_into_class: yes

watch:
  # - REL/
  - docs/
  - README.md
